### ISSUE TITLE
Question: Exception when setting merge operator

### ISSUE THREAD

**Issue by yoonsanghyeuk** [curiosity-ai/rocksdb-sharp#42]
When i set merge operator using **MergeOperators.Create** below exception is occurred. And i don't know this is my fault or not.

```
Unhandled exception. System.ArgumentException: The specified Type must not be a generic type. (Parameter 'delegate')
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegateInternal(Delegate d)
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate[TDelegate](TDelegate d)
   at Transitional.CurrentFramework.GetFunctionPointerForDelegate[T](T func)
   at RocksDbSharp.Options`1.SetMergeOperator(MergeOperator mergeOperator)
   at HeatmapReader.ReadInferenceList() in /home/yoon/Develop/dotnet_heatmap/HeatmapReader.cs:line 67
   at HeatmapReaderSample.Main(String[] args) in /home/yoon/Develop/dotnet_heatmap/Program.cs:line 269
```

Merge operator for test 
``` c#
public byte[] EmptyMerge(ReadOnlySpan<byte> key, MergeOperators.OperandsEnumerator operands, out bool success)
{
  success = true;
  return new byte[0];
}
```

And column family option
``` c#
var cfOptions = new ColumnFamilyOptions();
cfOptions.SetMergeOperator(MergeOperators.Create(
  name: "test",
  partialMerge: EmptyMerge,
  fullMerge: null
));

var cfs = new ColumnFamilies();
cfs.Add("inf_cf", cfOptions);
```

**Comment by yoonsanghyeuk** [comment]
Append more information.
dotnet version is 6 and rocksdbsharp version is 8.1.1.38086
And i opened db as secondary.
